common/models/RestaurantFloors.php
<?php

namespace common\models;

use common\models\BookReservations;
use common\models\Restaurants;
use common\models\RestaurantTables;
use Yii;

class RestaurantFloors extends \common\models\base\RestaurantFloorsBase
{
    public static function tableName()
    {
        return 'restaurant_floors';
    }
    /*public function beforeSave($insert) {
    $user_id = Yii::$app->user->id;
    if ($this->isNewRecord) {
    $this->setAttribute('created_by',$user_id);
    $this->setAttribute('created_at', date('Y-m-d H:i:s'));
    }
    $this->setAttribute('updated_at', date('Y-m-d H:i:s'));
    $this->setAttribute('updated_by',$user_id);

    return parent::beforeSave($insert);
    }*/

/**
 * @inheritdoc
 */
    public function rules()
    {
        return [
            [['name', 'status'], 'required'],
            [['restaurant_id', 'created_by', 'updated_by', 'status'], 'integer'],
            [['restaurant_id', 'created_at', 'updated_at', 'created_by', 'updated_by', 'is_deleted'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['restaurant_id'], 'exist', 'skipOnError' => true, 'targetClass' => Restaurants::className(), 'targetAttribute' => ['restaurant_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

/**
 * @inheritdoc
 */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'restaurant_id' => 'Restaurant ID',
            'name' => 'Name',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'status' => 'Status',
            "is_deleted" => "Delete Status",
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurant()
    {
        return $this->hasOne(Restaurants::className(), ['id' => 'restaurant_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantTables()
    {
        return $this->hasMany(RestaurantTables::className(), ['floor_id' => 'id']);
    }
    public function getBookReservations()
    {
        return $this->hasMany(BookReservations::className(), ['floor_id' => 'id']);
    }
}

backend/controllers/RestaurantFloorsController.php
<?php

namespace backend\controllers;

use backend\components\AdminCoreController;
use common\components\Common;
use common\models\RestaurantFloors;
use common\models\RestaurantFloorsSearch;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * RestaurantFloorsController implements the CRUD actions for RestaurantFloors model.
 */
class RestaurantFloorsController extends AdminCoreController
{
    /**
     * {@inheritdoc}
     */
/*    public function behaviors()
{
return [
'verbs' => [
'class' => VerbFilter::className(),
'actions' => [
'delete' => ['POST'],
],
],
];
}*/

    /**
     * Lists all RestaurantFloors models.
     * @return mixed
     */
    public function actionIndex()
    {
        $snRestaurantId = ($_GET['rid'] > 0) ? $_GET['rid'] : 0;
        $user = Common::get_user_role(Yii::$app->user->id, $flag = "1");
        if ((($user->role_id == Yii::$app->params['userroles']['manager']) && ($user->restaurant_id == $snRestaurantId)) || (($user->role_id == Yii::$app->params['userroles']['admin']) || ($user->role_id == Yii::$app->params['userroles']['super_admin']))) {
            $snRestaurantName = Common::get_name_by_id($snRestaurantId, $flag = "Restaurants");
            $searchModel = new RestaurantFloorsSearch();
            $dataProvider = $searchModel->backendSearch(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'snRestaurantName' => $snRestaurantName,
            ]);
        } else {
            throw new BadRequestHttpException('The requested page does not exist.');

        }
    }

    /**
     * Displays a single RestaurantFloors model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RestaurantFloors model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    /*  public function actionCreate()
    {
    $this->layout = "popup";
    $model = new RestaurantFloors();
    $snRestaurantId = ($_GET['rid'] > 0) ? $_GET['rid'] : 0;
    $snRestaurantName = Common::get_name_by_id($snRestaurantId,$flag = "Restaurants");
    $model->restaurant_id = $_GET['rid'];

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
    Yii::$app->session->setFlash( 'success', Yii::getAlias( '@restaurant_layout_add_message' ) );
    return Common::closeColorBox();
    return $this->redirect(['index', 'rid' => $model->restaurant_id]);
    }

    return $this->render('create', [
    'model' => $model,
    'snRestaurantName' => $snRestaurantName,
    ]);
    }*/

    /**
     * Updates an existing RestaurantFloors model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    /*  public function actionUpdate($id)
    {
    $this->layout = 'popup';
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
    Yii::$app->session->setFlash('success', Yii::getAlias('@restaurant_layout_update_message'));
    return Common::closeColorBox();
    return $this->redirect(['menu-categories/index']);
    }

    return $this->render('update', [
    'model' => $model,
    ]);
    }*/

    /**
     * Deletes an existing RestaurantFloors model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    /* public function actionDelete($id)
    {
    $this->findModel($id)->delete();

    Yii::$app->session->setFlash('success', Yii::getAlias('@restaurant_layout_delete_message'));
    return $this->redirect(['index', 'rid' => $model->restaurant_id]);
    }*/

    /**
     * Finds the RestaurantFloors model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RestaurantFloors the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RestaurantFloors::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/restaurant-floors/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\RestaurantFloors */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?= Html::encode($this->title) ?></div>
    </div>
    <div class="block-content collapse in">
<div class="restaurant-floors-form span12">

    <?php $form = ActiveForm::begin(); ?>

    <?php //echo $form->field($model, 'restaurant_id')->textInput() ?>
<div class="row">
    <div class="span3"><?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?></div>
</div>
<div class="row">
    <div class="span3"><?= $form->field($model, 'status')->dropDownList(Yii::$app->params['status']); ?></div>
</div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
    </div>
</div>

backend/views/restaurant-floors/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\RestaurantFloorsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="restaurant-floors-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index','rid'=>$_GET['rid']],
        'method' => 'get',
       /* 'options' => [
            'data-pjax' => 1
        ],*/
    ]); ?>

    <?php // $form->field($model, 'id') ?>

    <?php // $form->field($model, 'restaurant_id') ?>
  
  <div class="row">
    <div class="span3"><?= $form->field($model, 'name') ?></div>
   <div class="span3"><?= $form->field($model, 'status')->dropDownList(Yii::$app->params['user_status']);?></div>
 </div>
    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
          <?= Html::a(Yii::t('app', '<i class="icon-refresh"></i> clear'), Yii::$app->urlManager->createUrl(['restaurant-floors/index','rid'=>$_GET['rid'],"temp"=>"clear"]), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/restaurant-floors/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\RestaurantFloors */

$this->title = 'Create Restaurant Floor';
$this->params['breadcrumbs'][] = ['label' => 'Restaurant Floors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="restaurant-floors-create email-format-index">

    <?= $this->render('_form', [
        'model' => $model,
        'snRestaurantName' => $snRestaurantName,

    ]) ?>

</div>

backend/views/restaurant-floors/index.php
<?php

use common\components\Common;
use yii\grid\GridView;
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $searchModel common\models\RestaurantFloorsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Restaurant Floors';
$this->params['breadcrumbs'][] = ['label' => 'Manage Restaurants', 'url' => ['restaurants/index']];
$this->params['breadcrumbs'][] = ['label' => 'Manage Restaurants Floors', 'url' => ['restaurant-floors/index', 'rid' => $_GET['rid']]];
$this->params['breadcrumbs'][] = ['label' => $snRestaurantName];
?>
<div class="restaurant-floors-index email-format-index">
       <div class="email-format-index">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">Search Here</div>
        </div>
        <div class="block-content collapse in">
        <div class="restaurant-floors-form span12">

             <?=Html::a(Yii::t('app', '<i class="icon-filter icon-white"></i> Filter'), "javascript:void(0);", ['class' => 'btn btn-primary open_search']);?>
             <?php if (!empty($_REQUEST['RestaurantFloorsSearch']) || (!empty($_GET['temp']) && $_GET['temp'] == "clear")) {?>
                <div class="restaurantss-floors-serach common_search">
                 <?php echo $this->render('_search', ['model' => $searchModel]); ?>
                </div>
        <?php } else {?>
            <div class="restaurant-floors-serach common_search">
                 <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    <?php }?>
</div>
</div>
</div>
<div class="navbar navbar-inner block-header">
        <div class="muted pull-left">
            <?php echo Html::encode($this->title) . ' - ' . $snRestaurantName ?>
        </div>
       <!--  <div class="pull-right">
            <?php //Html::a(Yii::t('app', '<i class="icon-plus"></i> Add Layout'), Yii::$app->urlManager->createUrl(['restaurant-layout/create', 'rid' => ( $_GET['rid'] > 0 ) ? $_GET['rid'] : 0]), ['class' => 'btn btn-success colorbox_popup','onclick' => 'javascript:openColorBox(420,400);']) ?>
        </div> -->
    </div>
    <div class="block-content">
    <?php// Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?=GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        //'id',
        //'restaurant_id',
        'name',
        //'created_by',
        //'updated_by',
        [
            'attribute' => 'status',
            'filter' => Yii::$app->params['status'],
            'value' => function ($data) {
                return Yii::$app->params['status'][$data->status];
            },
        ],

        //'created_at',
        //'updated_at',

        [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{tables}',
            'buttons' => [
                /* 'update' => function ($url, $model) {
                $flag = 2;
                $url = Yii::$app->urlManager->createurl(['restaurant-layout/update', 'rid' => $model->restaurant_id, 'id' => $model->id]);
                return Common::template_update_tag_button($url, $model, $flag);
                },*/
                'tables' => function ($url, $model) {
                    $title = "Manage Tables";
                    $flag = 4;
                    $url = Yii::$app->urlManager->createUrl(['restaurant-tables/index', 'rid' => $model->restaurant_id, 'lid' => $model->id]);
                    return Common::template_view_gallery_button($url, $model, $title, $flag);

                },
                /* 'delete' => function ($url, $model) {
            $flag = 1;
            $url = Yii::$app->urlManager->createurl(['restaurant-layout/delete', 'rid' => $model->restaurant_id, 'id' => $model->id]);
            $confirmmessage = "Are you sure you want to delete this Layout?";
            return Common::template_delete_button($url, $model,$confirmmessage, $flag);
            },*/
            ],
        ],
    ],
]);?>

    <?php// Pjax::end(); ?>
   </div>
</div>
<script type="text/javascript">
$( document ).ready(function() {
    $('.restaurant-floors-serach').hide();
        $('.open_search').click(function(){
            $('.restaurant-floors-serach').toggle();
        });
    });

</script>

backend/views/restaurant-floors/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\RestaurantFloors */

$this->title = 'Update Restaurant Floor: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Restaurant Floors', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="restaurant-floor-update email-format-index">

    <?= $this->render('_form', [
        'model' => $model,
      //  'snRestaurantName' => $snRestaurantName,
    ]) ?>

</div>

backend/views/restaurant-floors/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\RestaurantFloors */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Restaurant Floors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="restaurant-floors-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'restaurant_id',
            'name',
            'created_by',
            'updated_by',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>