common/models/RestaurantTables.php
<?php

namespace common\models;

use Yii;

class RestaurantTables extends \common\models\base\RestaurantTablesBase
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'restaurant_tables';
    }

    /* public function beforeSave($insert) {
    $user_id = Yii::$app->user->id;
    if ($this->isNewRecord) {
    $this->setAttribute('created_by',$user_id);
    $this->setAttribute('created_at', date('Y-m-d H:i:s'));
    }
    $this->setAttribute('updated_at', date('Y-m-d H:i:s'));
    $this->setAttribute('updated_by',$user_id);

    return parent::beforeSave($insert);
    }*/
/**
 * @inheritdoc
 */

    public function rules()
    {
        return [
            [['name', 'min_capacity', 'max_capacity', 'status'], 'required'],
            [['restaurant_id', 'floor_id', 'min_capacity', 'max_capacity', 'created_by', 'updated_by', 'status'], 'integer'],
            [['restaurant_id', 'floor_id', 'width', 'height', 'x_cordinate', 'y_cordinate', 'shape', 'created_at', 'updated_at', 'created_by', 'updated_by', 'status', 'is_deleted'], 'safe'],
            [['name'], 'string', 'max' => 250],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['floor_id'], 'exist', 'skipOnError' => true, 'targetClass' => RestaurantFloors::className(), 'targetAttribute' => ['floor_id' => 'id']],
            [['restaurant_id'], 'exist', 'skipOnError' => true, 'targetClass' => Restaurants::className(), 'targetAttribute' => ['restaurant_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

/**
 * @inheritdoc
 */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'restaurant_id' => 'Restaurant ID',
            'floor_id' => 'Floor ID',
            'name' => 'Name',
            'width' => 'Width',
            'height' => 'Height',
            'x_cordinate' => 'X Cordinate',
            'y_cordinate' => 'Y Cordinate',
            'shape' => 'Shape',
            'min_capacity' => 'Min Capacity',
            'max_capacity' => 'Max Capacity',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'status' => 'Status',
            "is_deleted" => "Delete Status",
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLayout()
    {
        return $this->hasOne(RestaurantFloors::className(), ['id' => 'floor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurant()
    {
        return $this->hasOne(Restaurants::className(), ['id' => 'restaurant_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'updated_by']);
    }
    public function getBookReservations()
    {
        return $this->hasMany(BookReservations::className(), ['table_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservations()
    {
        return $this->hasMany(Reservations::className(), ['table_id' => 'id']);
    }

}

common/models/Restaurants.php
<?php

namespace common\models;

use common\models\RestaurantFloors;
use common\models\RestaurantMealTimes;
use common\models\RestaurantMenu;
use common\models\RestaurantTables;
use common\models\RestaurantWorkingHours;
use Yii;
use yii\helpers\ArrayHelper;

class Restaurants extends \common\models\base\RestaurantsBase
{
    public static function tableName()
    {
        return 'restaurants';
    }

/**
 * @inheritdoc
 */
    public function beforeSave($insert)
    {
        $user_id = Yii::$app->user->id;
        if ($this->isNewRecord) {
            $this->setAttribute('created_by', $user_id);
            $this->setAttribute('created_at', date('Y-m-d H:i:s'));
        }
        $this->setAttribute('updated_at', date('Y-m-d H:i:s'));
        $this->setAttribute('updated_by', $user_id);

        return parent::beforeSave($insert);
    }
    public static function RestaurantsDropDown()
    {
        //->where(['status'=>Yii::$app->params['department_active_status']])
        return ArrayHelper::map(Restaurants::find()->orderBy('name')->asArray()->all(), 'id', 'name');
    }
    public function rules()
    {
        return [
            [['name', 'address', 'contact_no', 'email', 'max_stay_time_after_reservation', 'description'], 'required'],
            [['description'], 'string', 'max' => 100],
            [['email'], 'email'],
            ['email', 'validateEmail'],
            ['contact_no', 'is10NumbersOnly'],
            [['description', 'address'], 'string'],
            [['pincode', 'contact_no', 'status'], 'integer'],
            [['lattitude', 'longitude'], 'number'],
            [['max_stay_time_after_reservation', 'created_by', 'updated_by', 'photo', 'created_at', 'updated_at'], 'safe'],
            [['name', 'city', 'country', 'website', 'email'], 'string', 'max' => 255],
            [['state'], 'string', 'max' => 250],
        ];
    }
    public function is10NumbersOnly($attribute)
    {
        if (!preg_match('/^[0-9]{10}$/', $this->$attribute)) {
            $this->addError($attribute, 'Invalid contact Number.');
        }
    }
    public function validateEmail()
    {
        $ASvalidateemail = Restaurants::find()->where('email = "' . $this->email . '" and id != "' . $this->id . '"')->all();
        if (!empty($ASvalidateemail)) {
            $this->addError('email', 'This email address already registered.');
            return true;
        }
    }

/**
 * @inheritdoc
 */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'photo' => "Photo",
            'address' => 'Address',
            'city' => 'City',
            'state' => 'State',
            'country' => 'Country',
            'pincode' => 'Pincode',
            'lattitude' => 'Lattitude',
            'longitude' => 'Longitude',
            'website' => 'Website',
            'contact_no' => 'Contact No',
            'email' => 'Email',
            'max_stay_time_after_reservation' => 'Max Stay Time After Reservation',
            'status' => 'Status',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantFloorss()
    {
        return $this->hasMany(RestaurantFloors::className(), ['restaurant_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantMenus()
    {
        return $this->hasMany(RestaurantMenu::className(), ['restaurant_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantTables()
    {
        return $this->hasMany(RestaurantTables::className(), ['restaurant_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantWorkingHours()
    {
        return $this->hasMany(RestaurantWorkingHours::className(), ['restaurant_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurentMealTimes()
    {
        return $this->hasMany(RestaurantMealTimes::className(), ['restaurant_id' => 'id']);
    }
}

backend/controllers/RestaurantsController.php
<?php

namespace backend\controllers;

use backend\components\AdminCoreController;
use common\components\Common;
use common\models\RestaurantMealTimes;
use common\models\RestaurantMealTimesSearch;
use common\models\Restaurants;
use common\models\RestaurantsSearch;
use common\models\RestaurantWorkingHours;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * RestaurantsController implements the CRUD actions for Restaurants model.
 */
class RestaurantsController extends AdminCoreController
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    /**
     * {@inheritdoc}
     */
    /* public function behaviors()
    {
    return [
    'verbs' => [
    'class' => VerbFilter::className(),
    'actions' => [
    'delete' => ['POST'],
    ],
    ],
    ];
    }*/

    /**
     * Lists all Restaurants models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RestaurantsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Restaurants model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = 'popup';
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionTest()
    {
        return $this->render('test');
    }

    /**
     * Creates a new Restaurants model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Restaurants();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            $file = \yii\web\UploadedFile::getInstance($model, 'photo');
            if (!empty($file)) {
                $file_name = $file->basename . "_" . uniqid() . "." . $file->extension;
                $model->photo = $file_name;
                $file->saveAs(Yii::getAlias('@root') . '/frontend/web/uploads/' . $file_name);
            }
            $model->save();
            $mealTimes = Yii::$app->params['meal_times'];
            foreach ($mealTimes as $key => $value) {
                $modelMealTimes = new RestaurantMealTimes();
                $modelMealTimes->restaurant_id = $model->id;
                $modelMealTimes->meal_type = $key;
                $modelMealTimes->status = "1";
                $modelMealTimes->save(false);
            }

            Yii::$app->session->setFlash('success', Yii::getAlias('@restaurant_add_message'));
            return $this->redirect(['restaurants/index']);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Restaurants model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $user = Common::get_user_role(Yii::$app->user->id, $flag = "1");
        if ((($user->role_id == Yii::$app->params['userroles']['manager']) && ($user->restaurant_id == $id)) || (($user->role_id == Yii::$app->params['userroles']['admin']) || ($user->role_id == Yii::$app->params['userroles']['super_admin']))) {
            $milestones = ArrayHelper::map(RestaurantMealTimes::find()->where(['restaurant_id' => $id])->asArray()->all(), 'meal_type', 'meal_type');
            $searchModel = new RestaurantMealTimesSearch();
            $queryParams = array_merge(array(), Yii::$app->request->getQueryParams());
            $queryParams["RestaurantMealTimesSearch"]["restaurant_id"] = $id;
            $dataProvider = $searchModel->backendSearch($queryParams);
            $model = $this->findModel($id);
            $old_image = $model->photo;

            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $file = \yii\web\UploadedFile::getInstance($model, 'photo');
                if (!empty($file)) {
                    $delete = $model->oldAttributes['photo'];
                    $file_name = $file->basename . "_" . uniqid() . "." . $file->extension;

                    $model->photo = $file_name;
                    if (!empty($old_image) && file_exists(Yii::getAlias('@root') . '/frontend/web/uploads/' . $old_image)) {
                        unlink(Yii::getAlias('@root') . '/frontend/web/uploads/' . $old_image);
                    }
                    $file->saveAs(Yii::getAlias('@root') . '/frontend/web/uploads/' . $file_name, false);
                    $model->photo = $file_name;
                } else {
                    $model->photo = $old_image;
                }
                $model->save();
                Yii::$app->session->setFlash('success', Yii::getAlias('@restaurant_update_message'));
                return $this->redirect(['restaurants/index']);
            }

            return $this->render('update', [
                'model' => $model,
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            throw new BadRequestHttpException('The requested page does not exist.');
        }
    }

    /**
     * Deletes an existing Restaurants model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $user = Common::get_user_role(Yii::$app->user->id, $flag = "1");
        if ((($user->role_id == Yii::$app->params['userroles']['manager']) && ($user->restaurant_id == $id)) || (($user->role_id == Yii::$app->params['userroles']['admin']) || ($user->role_id == Yii::$app->params['userroles']['super_admin']))) {
            $model = $this->findModel($id);
            $model->is_deleted = "1";
            $model->save(false);
            Yii::$app->session->setFlash('success', Yii::getAlias('@restaurant_delete_message'));
            return $this->redirect(['index']);
        } else {
            throw new BadRequestHttpException('The requested page does not exist.');
        }
    }

    public function actionUpdateWorkinghours($rid)
    {

        $this->layout = 'popup';
        //GET PROJECT NAME BY PROJECT ID
        $user = Common::get_user_role(Yii::$app->user->id, $flag = "1");
        if ((($user->role_id == Yii::$app->params['userroles']['manager']) && ($user->restaurant_id == $rid)) || (($user->role_id == Yii::$app->params['userroles']['admin']) || ($user->role_id == Yii::$app->params['userroles']['super_admin']))) {
            $snRestaurantName = Restaurants::find()->where("id=$rid")->one();
            $arrWeeks = Yii::$app->params['week_days'];
            $week_days_hours_details = array();
            foreach ($arrWeeks as $key => $week) {
                $weekDetails[$key] = $week;
                $days = RestaurantWorkingHours::find()->where(['restaurant_id' => $rid, 'weekday' => $key])->one();

                if (!empty($days)) {
                    $week_days_hours_details[$key] = $days;
                } else {
                    $week_days_hours_details[$key] = new RestaurantWorkingHours();
                }
            }
            if (Yii::$app->request->post()) {
                $arrRequestFields = $_REQUEST['RestaurantWorkingHours'];
                $postData = Yii::$app->request->post();
                $postData = $postData['RestaurantWorkingHours'];
                foreach ($postData as $key => $value) {
                    $week_days_hours_details[$key]->load($value);
                    $week_days_hours_details[$key]['weekday'] = $key;
                    $week_days_hours_details[$key]['hours24'] = $value['hours24'];
                    $week_days_hours_details[$key]['restaurant_id'] = $rid;
                    $week_days_hours_details[$key]['opening_time'] = date("H:i:s", strtotime($value['opening_time']));
                    $week_days_hours_details[$key]['closing_time'] = date("H:i:s", strtotime($value['closing_time']));
                    $week_days_hours_details[$key]['status'] = $value['status'];
                    $week_days_hours_details[$key]->save();

                }
                Yii::$app->session->setFlash('success', Yii::getAlias('@hours_update_message'));
                return Common::closeColorBox();
            }
            return $this->render('hours', [
                'snRestaurantName' => $snRestaurantName->name,
                'week_days_hours_details' => $week_days_hours_details,
                'weekDetails' => $weekDetails,
            ]);
        } else {
            throw new BadRequestHttpException('The requested page does not exist.');

        }
    }

    /**
     * Finds the Restaurants model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Restaurants the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Restaurants::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionSwitchoffRestaurant()
    {
        if (!empty($_POST)) {
            $restaurant = Restaurants::find()->where(['id' => $_POST['restaurant_id']])->one();

backend/views/restaurants/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Restaurants */
$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Restaurants',
]);
$this->params['breadcrumbs'][] = ['label' => 'Manage Restaurants', 'url' => ['restaurants/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="restaurants-create email-format-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/restaurants/index.php
<?php

use common\components\Common;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models\RestaurantsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Restaurants';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="restaurants-index email-format-index">
      <div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Search Here</div>
    </div>
        <div class="block-content collapse in">
        <div class="tags-form span12">

     <?=Html::a(Yii::t('app', '<i class="icon-filter icon-white"></i> Filter'), "javascript:void(0);", ['class' => 'btn btn-primary open_search']);?>
     <?php if (!empty($_REQUEST['RestaurantsSearch']) || (!empty($_GET['temp']) && $_GET['temp'] == "clear")) {?>
        <div class="restaurantss-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
<?php } else {?>
    <div class="restaurants-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    <?php }?>
</div>
</div>
</div>
<div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
        <?php $user_role = Common::get_user_role(Yii::$app->user->id, $flag = 0);
if ($user_role != Yii::$app->params['userroles']['manager']) {?>

        <div class="pull-right">
        <?=Html::a(Yii::t('app', '<i class="icon-plus"></i> Add Restaurant'), ['create'], ['class' => 'btn btn-success'])?>
       </div>
<?php }
?>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
  <div class="block-content">
        <div class="goodtable">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?=GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        // 'id',
        [
            'attribute' => 'name',
            //  'filter' => Yii::$app->params['status'],
            'filterOptions' => ["style" => "width:16%;text-align:center;"],
            'headerOptions' => ["style" => "width:16%;text-align:center;"],
            'contentOptions' => ["style" => "width:16%;text-align:center;"],
            'value' => function ($data) {
                return $data->name;
            },
        ],
        [
            'attribute' => 'description',
            //'visible'=>( !empty( $_GET['tid'] ) ) ? false : true,
            'format' => 'raw',
            'value' => function ($data) {
                $ssText = Common::get_substr($data->description, 20);
                return Html::a($ssText, ['view', 'id' => $data->id], ['class' => 'colorbox_popup', 'onclick' => 'javascript:openColorBox(700,650);']);
            },
        ],
        //  'description:ntext',
        [
            'attribute' => 'address',
            //  'filter' => Yii::$app->params['status'],
            'filterOptions' => ["style" => "width:25%;text-align:center;"],
            'headerOptions' => ["style" => "width:25%;text-align:center;"],
            'contentOptions' => ["style" => "width:25%;text-align:center;"],
            'value' => function ($data) {
                return $data->address;
            },
        ],
        //'city',
        //'state',
        [
            'attribute' => 'country',
            //  'filter' => Yii::$app->params['status'],
            'filterOptions' => ["style" => "width:10%;text-align:center;"],
            'headerOptions' => ["style" => "width:10%;text-align:center;"],
            'contentOptions' => ["style" => "width:10%;text-align:center;"],
            'value' => function ($data) {
                return $data->country;
            },
        ],
        //'pincode',
        //'lattitude',
        //'longitude',
        [
            'attribute' => 'website',
            //  'filter' => Yii::$app->params['status'],
            'filterOptions' => ["style" => "width:10%;text-align:center;"],
            'headerOptions' => ["style" => "width:10%;text-align:center;"],
            'contentOptions' => ["style" => "width:10%;text-align:center;"],
            'value' => function ($data) {
                return $data->website;
            },
        ],
        'contact_no',
        //'email:email',
        'max_stay_time_after_reservation',
        [
            'attribute' => 'status',
            'filter' => Yii::$app->params['status'],
            'filterOptions' => ["style" => "width:13%;"],
            'headerOptions' => ["style" => "width:13%;"],
            'contentOptions' => ["style" => "width:13%;"],
            'value' => function ($data) {
                return Yii::$app->params['status'][$data->status];
            },
        ],
        [
            'attribute' => 'status',
            'filter' => Yii::$app->params['status'],
            'format' => 'raw',
            'filterOptions' => ["style" => "width:13%;"],
            'headerOptions' => ["style" => "width:13%;"],
            'contentOptions' => ["style" => "width:13%;"],
            'value' => function ($data) {
                $url = "#";
                $status = ($data->status == 1) ? "true" : "false";
                $class = ($data->status == 1) ? "switch2" : "";
                return Html::a('<label class="switch"><input type="checkbox" value="' . $status . '" onclick="switchoff_restaurant(' . $data->id . ');" id="' . $data->id . '" class="' . $class . '"><span class="slider round"></span></label>', $url);
            },
        ],

        //'created_at',
        //'updated_at',

        [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{update}{manage_working_hours}{manage_gallery}{manage_menu}{manage_layout}{manage_reservations}{delete}',
            'buttons' => [
                'update' => function ($url, $model) {
                    $flag = 1;
                    return Common::template_update_button($url, $model, $flag);
                },
                'delete' => function ($url, $model) {
                    $flag = 1;
                    $confirmmessage = "Are you sure you want to delete this Restaurant?";
                    return Common::template_delete_button($url, $model, $confirmmessage, $flag);
                },
                'manage_gallery' => function ($url, $model) {
                    $title = "Manage Gallery";
                    $flag = 2;
                    $url = Yii::$app->urlManager->createUrl(['restaurants-gallery/index', 'rid' => $model->id]);
                    return Common::template_view_gallery_button($url, $model, $title, $flag);

                },
                'manage_menu' => function ($url, $model) {
                    $title = "Manage Menu Items";
                    $flag = 1;
                    $url = Yii::$app->urlManager->createUrl(['restaurant-menu/index', 'rid' => $model->id]);
                    return Common::template_view_gallery_button($url, $model, $title, $flag);

                },
                'manage_working_hours' => function ($url, $model) {
                    $title = "manage Restaurant's Working Hours";
                    $flag = 1;
                    $url = Yii::$app->urlManager->createUrl(['restaurants/update-workinghours', 'rid' => $model->id]);
                    return Common::template_update_permission_button($url, $model, $title, $flag);

                },
                'manage_layout' => function ($url, $model) {
                    $title = "manage Restaurant's Layout";
                    $flag = 3;
                    $url = Yii::$app->urlManager->createUrl(['restaurant-floors/index', 'rid' => $model->id]);
                    return Common::template_view_gallery_button($url, $model, $title, $flag);

                },
                'manage_reservations' => function ($url, $model) {
                    $title = "Manage Reservations";
                    $flag = 4;
                    $url = Yii::$app->urlManager->createUrl(['reservations/index', 'restaurant_id' => $model->id]);
                    return Common::template_view_gallery_button($url, $model, $title, $flag);

                },

            ],
        ],
    ],
]);?>
 </div>
    </div>
</div>
<script type="text/javascript">
$( document ).ready(function() {
    $('.restaurants-serach').hide();
        $('.open_search').click(function(){
            $('.restaurants-serach').toggle();
        });
    });
/*function switchoff_restaurant(id){
      $("#"+id).toggleClass("switch2");
   if ($("#"+id).is(':checked')) {
   $("#"+id).attr('value', 'true');
      $.ajax({
     url: "restaurants/switchoff-restaurant",
     type: 'post',
     dataType: 'json',
     data: {
               checked: true,
               restaurant_id:id,
           },
     success: function (data) {
      if(data == "success"){
       alert("success");
       return false;
      }else if(data=="reported"){
        alert("You have already reported this question");
        location.reload();
      }else{
        alert("something went wrong");
      }
     }
  });
 } else {
   $("#"+id).attr('value', 'false');
         $.ajax({
     url: "restaurants/switchoff-restaurant",
     type: 'post',
     dataType: 'json',
     data: {
               checked: false,
               restaurant_id:id,
           },
     success: function (data) {
      if(data == "success"){
       alert("success");
        location.reload();
      }else if(data=="error"){
        alert("Something went wrong");
         location.reload();
      }
     }
  });
 }
//document.getElementById(id).checked = false;
}*/




/*   $(document).ready(function(){
 $("input").click(function(){
   $("input").toggleClass("switch2");
   if ($(this).is(':checked')) {
   $(this).attr('value', 'true');
 } else {
   $(this).attr('value', 'false');
 }
//      if ($(this).hasClass('switch2')) {
//    $(this).attr('value', 'true');
//  } else {
//    $(this).attr('value', 'false');
//  }
 });
});*/
function switchoff_restaurant(id){
      $("#"+id).toggleClass("switch2");
   if ($("#"+id).val() == "true") {
   $("#"+id).attr('value', 'false');
      $.ajax({
     url: "restaurants/switchoff-restaurant",
     type: 'post',
     dataType: 'json',
     data: {
               checked: false,
               restaurant_id:id,
           },
     success: function (data) {
      if(data == "success"){
         alert("Restaurant is inactive for reservations.");
        location.reload();
      }else if(data=="error"){
        alert("Something went wrong");
         location.reload();
      }
     }
  });
 } else {
   $("#"+id).attr('value', 'true');
         $.ajax({
     url: "restaurants/switchoff-restaurant",
     type: 'post',
     dataType: 'json',
     data: {
               checked: true,
               restaurant_id:id,
           },
     success: function (data) {
      if(data == "success"){
       alert("Restaurant is active for the reservations now");
        location.reload();
      }else if(data=="error"){
        alert("Something went wrong");
         location.reload();
      }
     }
  });
 }
//document.getElementById(id).checked = false;
}
</script>