backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\components\AdminCoreController;
use common\components\Common;
use common\models\AdminLoginForm;
use common\models\ChangePasswordForm;
use common\models\EmailFormat;

//Load common models
use common\models\ForgotPasswordForm;
use common\models\Users;
use Yii;

/**
 * Site controller
 */
class SiteController extends AdminCoreController
{
    public function beforeAction($action)
    {

        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout = "login";
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new AdminLoginForm();
        $forgotPasswordModel = new ForgotPasswordForm();
        //set scenario for this model
        $forgotPasswordModel->scenario = 'forgot_password';

        //ajax validation code start
        if (Yii::$app->request->isAjax && $forgotPasswordModel->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return \yii\widgets\ActiveForm::validate($forgotPasswordModel);
        }

        //compare login
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        } elseif ($forgotPasswordModel->load(Yii::$app->request->post()) && $forgotPasswordModel->validate()) {

            //successfully validte after get user details.
            $usermodel = Users::findOne(['email' => $forgotPasswordModel->email]);
            if (!empty($usermodel)) {
                //generate rendome new password
                $password = Common::generatePassword();
                //new password convert to md5
                $Npwd = md5($password);
                $usermodel->password = $Npwd;
                //save password
                $usermodel->Save();

                //Get email template into database for forgot password
                $emailformatemodel = EmailFormat::findOne(["title" => 'forgot_password', "status" => '1']);
                if ($emailformatemodel) {

                    //create template file
                    $AreplaceString = array('{password}' => $password, '{username}' => $usermodel->first_name, '{email}' => $usermodel->email);
                    $body = Common::MailTemplate($AreplaceString, $emailformatemodel->body);

                    //send email for new generated password
                    Common::sendMailToUser($forgotPasswordModel->email, Yii::$app->params['adminEmail'], $emailformatemodel->subject, $body);
                    Yii::$app->session->setFlash('success', Yii::getAlias('@admin_user_forget_password_msg'));
                }
                return $this->goBack();
                //return $this->redirect(Yii::$app->urlManager->createUrl(['site/index']));
            }
        } else {
            return $this->render('login', compact('model', 'forgotPasswordModel'));
        }
    }

    public function actionChangePassword()
    {
        $model = new ChangePasswordForm();

        //ajax validation code start
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return \yii\widgets\ActiveForm::validate($model);
        }
        // set data into model and validate model
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // Get user details
            $usermodel = Users::findOne(Yii::$app->user->id);
            //set password
            $usermodel->password = md5($model->newPassword);
            //save password
            $usermodel->save(false);

            Yii::$app->session->setFlash('success', Yii::getAlias('@admin_user_change_password_msg'));
            return $this->redirect(Yii::$app->urlManager->createUrl(['site/change-password']));
        } else {
            return $this->render('change_password', compact('model'));
        }
    }
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\components\Common;
use common\models\ContactUs;
use common\models\EmailFormat;
use common\models\LoginForm;
use common\models\MenuCategories;
use common\models\RestaurantMenu;
use common\models\Restaurants;
use common\models\RestaurantsGallery;
use common\models\Users;
use frontend\components\FrontCoreController;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends FrontCoreController
{
    public function beforeAction($action)
    {

        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /*  public function actions()
    {
    return [
    'error' => [
    'class' => 'yii\web\ErrorAction',
    ],
    'captcha' => [
    'class' => 'yii\captcha\CaptchaAction',
    'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
    ],
    ];
    }*/

    public function actionIndex()
    {
        $this->layout = "landingpage";

        $model = new LoginForm();
        $model2 = new SignupForm();

        if (isset($_REQUEST['hidden']) && !empty($_REQUEST['hidden']) && ($_REQUEST['hidden'] == 'login')) {
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                if (isset($_GET['rid']) && !empty($_GET['rid'])) {
                    return $this->redirect(\Yii::$app->urlManager->createUrl(['reservations/create', 'rid' => $_GET['rid']]));
                } else {
                    return $this->redirect(\Yii::$app->urlManager->createUrl(['site/restaurants']));
                }
            }
        }
        if (isset($_REQUEST['hidden']) && !empty($_REQUEST['hidden']) && ($_REQUEST['hidden'] == 'signup')) {
            if ($model2->load(Yii::$app->request->post())) {
                if ($user = $model2->signup()) {
                    Yii::$app->session->setFlash('success', Yii::getAlias('@signup_success'));
                    return $this->redirect(\Yii::$app->urlManager->createUrl(['site/index']));

                    /*   if (Yii::$app->getUser()->login($user)) {
                if (isset($_GET['rid']) && !empty($_GET['rid'])) {
                return $this->redirect(\Yii::$app->urlManager->createUrl(['reservations/create', 'rid' => $_GET['rid']]));
                } else {
                }
                }*/
                }
            }

        }
        return $this->render('frontpage', [
            "model" => $model,
            "model2" => $model2,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['site/index']);
    }

    public function actionRequestPasswordReset()
    {
        $this->layout = "forgot_password";
        $model = new PasswordResetRequestForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', Yii::getAlias('Check your email for Reset Password.'));
                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('fail', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }
        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        $this->layout = "forgot_password";
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    public function actionRestaurants()
    {
        $this->layout = "restaurant_list";

        if (isset($_REQUEST['search_restaurant']) && !empty($_REQUEST['search_restaurant'])) {

            $query = Restaurants::find()->where("name LIKE '" . $_REQUEST['search_restaurant'] . "%'");
            $snRestaurantsArr = Restaurants::find()->where("name LIKE '" . $_REQUEST['search_restaurant'] . "%'")->all();
        } else {
            $query = Restaurants::find();
            $snRestaurantsArr = Restaurants::find()->all();
        }
        $pagination = new Pagination(['totalCount' => $query->count(), 'pageSize' => 9]);
        $models = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('restaurants', [
            'Restaurants' => $snRestaurantsArr,
            'models' => $models,
            'pagination' => $pagination,
        ]);
    }

    public function actionRestaurantDetails($rid)
    {

        $this->layout = "detail";

        if (isset($rid) && !empty($rid)) {

            $snRestaurantsDetail = Restaurants::find()->where(['id' => $rid])->one();
            $snRestaurantMenuCategoryArr = MenuCategories::find()->where(["status" => "1"])->all();
            $snRestaurantMenusArr = RestaurantMenu::find()->where(['restaurant_id' => $rid, 'status' => "1"])->all();
            $query = RestaurantsGallery::find()->where(['restaurant_id' => $rid, 'status' => "1"]);
            $snRestaurantgallerysArr = RestaurantsGallery::find()->where(['restaurant_id' => $rid, 'status' => "1"])->all();
            $pagination = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3]);
            $models = $query->offset($pagination->offset)
                ->limit($pagination->limit)
                ->all();
            $snRestaurantWorkingHours = $snRestaurantsDetail->getRestaurantWorkingHours();
            $snRestaurantWorkingHoursArr = $snRestaurantWorkingHours->all();
            //   p($snRestaurantWorkingHoursArr);
            $snRestaurantMealTimes = $snRestaurantsDetail->getRestaurentMealTimes();
            $snRestaurantMealTimesArr = $snRestaurantMealTimes->all();

            /*   $snRestaurantFloorssArr = $snRestaurantsDetail->getRestaurantFloorss();
            $snRestaurantTablesArr = $snRestaurantsDetail->getRestaurantTables();*/

            //p($snRestaurantsDetail);
        }
        return $this->render('restaurant_detail', [
            'rid' => $rid,
            'snRestaurantsDetail' => $snRestaurantsDetail,
            'snRestaurantMenuCategoryArr' => $snRestaurantMenuCategoryArr,
            'snRestaurantMenusArr' => $snRestaurantMenusArr,
            'snRestaurantMealTimesArr' => $snRestaurantMealTimesArr,
            'snRestaurantWorkingHoursArr' => $snRestaurantWorkingHoursArr,
            'snRestaurantgallerysArr' => $snRestaurantgallerysArr,
            'models' => $models,
            'pagination' => $pagination,
        ]);
    }
    public function actionContactUs()
    {
        if (isset($_POST) && !empty($_POST)) {
            $name = $_POST['ContactUs']['name'];
            $fromEmail = $_POST['ContactUs']['email'];
            $message = $_POST['ContactUs']['message'];
            $model = new ContactUs();
            $model->name = $name;
            $model->email = $fromEmail;
            $model->message = $message;

            ///////////////////////////////////////////////////////////
            //Get email template into database for forgot password
            $emailformatemodel = EmailFormat::findOne(["title" => 'contact_us', "status" => '1']);
            if ($emailformatemodel) {
                //create template file
                $AreplaceString = array('{name}' => $name, '{message}' => $message);

                $body = Common::MailTemplate($AreplaceString, $emailformatemodel->body);

                //send email
                $mail = Common::sendMailToUser(Yii::$app->params['adminEmail'], $fromEmail, $emailformatemodel->subject, $body);
                if ($mail) {
                    $model->save(false);
                    return "success";
                } else {
                    return "fail";
                }
            }
        }
    }
    public function actionEmailVerify($verify, $e)
    {
        $email = base64_decode($e);
        $verificationcode = base64_decode($verify);
        $user = Users::findOne(['email' => $email, 'verification_code' => $verificationcode]);
        if (!empty($user) && ($user->is_code_verified == "0")) {
            $user->is_code_verified = "1";
            $user->save(false);
            Yii::$app->getSession()->setFlash('success', Yii::getAlias('Your Email is successfully verified.Please login in website.'));
            return $this->redirect(\Yii::$app->urlManager->createUrl(['site/index']));
        } else if (!empty($user) && ($user->is_code_verified == "1")) {
            Yii::$app->getSession()->setFlash('fail', 'Your Email is already verified.');
            return $this->redirect(\Yii::$app->urlManager->createUrl(['site/index']));
        } else {
            Yii::$app->getSession()->setFlash('fail', 'Something went wrong please check your link');
            return $this->redirect(\Yii::$app->urlManager->createUrl(['site/index']));
        }
    }

}

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/frontpage.php
<?php
use common\models\ContactUs;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
$this->title = 'Chiefs RS';
?>
  <div class="col-md-9">
            <?php
$url = Yii::getAlias('@web') . "/img/logo.png";
?>
            <a class="brand" href="#"><img src="<?php echo $url; ?>"></a>
            <h1 class="site-heading site-animate mb-3">Welcome to Chiefs RS reservation System</h1>
            <h2 class="h5 site-subheading mb-5 site-animate">Please book your restaurant now</h2>
          <form name="search" id="search" method="post" action="<?=Yii::$app->urlManager->createUrl(['site/restaurants'])?>">
            <p><input type="text" name="search_restaurant" class="search_text site-animate" placeholder="Search for a Restaurant"><a href="javascript:void(0);" onclick="document.getElementById('search').submit();" class="btn btn-outline-white btn-lg site-animate"><i class="fas fa-search" style="text-align:center;"></i> </a></p>
          </form>
          </div>
          <?php if (Yii::$app->user->isGuest) {
    ?>
  <div class="form-w3ls col-md-3">

    <ul class="tab-group cl-effect-4">
        <?php

    $signup_active = "";
    $login_active = "";
    if (isset($_REQUEST['hidden']) && !empty($_REQUEST['hidden']) && ($_REQUEST['hidden'] == 'signup')) {
        $signup_active = "active";
        $login_active = "";

    } else {
        $signup_active = "";
        $login_active = "active";

    }?>
        <li class="tab login_tab <?php echo $login_active ?>"><a href="#signin-agile">Log In</a></li>
        <li class="tab signup_tab <?php echo $signup_active ?>"><a href="#signup-agile">Join Us</a></li>
    </ul>

    <div class="tab-content">
        <div id="signin-agile">
            <div class="logo">
    <img src="<?php echo Yii::getAlias('@web') . "/themes/chiefsrs/images/chief-rs_logo.png"; ?>" alt="ChiefsRS Logo">
  </div>
       <?php

    $form = ActiveForm::begin(['id' => 'login-form', 'method' => 'post']);?>
                <?=$form->field($model, 'email')->textInput(['class' => 'form-control login_email input_field_design', 'placeholder' => 'Email' /*'onfocus'=>"this.value = '';","onblur"=>"if (this.value == '') {this.value = 'Email';}"*/])->label(false);?>
                <?=$form->field($model, 'password')->passwordInput(['class' => 'form-control input_field_design', 'placeholder' => 'Password'])->label(false);?>
                <input type="text" name="hidden" value="login" hidden="true">
                <p class="forgot"> <a href="<?=Yii::$app->urlManager->createUrl(['site/request-password-reset']);?>">Forgot Password?</a> </p>

                <div class="form-group">
                    <?=Html::submitButton('Log In', ['class' => 'sign-in', 'name' => 'login-button'])?>
                </div>
            <?php ActiveForm::end();?>
    </div>
    <div id="signup-agile">

       <?php //  $model2 = new SignupForm();
    $form2 = ActiveForm::begin(['id' => 'form-signup', 'method' => 'post']);?>
     <?=$form2->field($model2, 'first_name')->textInput(['class' => 'form-control input_field_design', 'placeholder' => 'First Name'])->label(false);?>
                    <?=$form2->field($model2, 'last_name')->textInput(['class' => 'form-control input_field_design', 'placeholder' => 'Last Name'])->label(false);?>
                    <?=$form2->field($model2, 'email')->textInput(['class' => 'form-control input_field_design', 'placeholder' => 'Email'])->label(false);?>

                    <?=$form2->field($model2, 'password')->passwordInput(['class' => 'form-control input_field_design', 'placeholder' => 'Password'])->label(false);?>
                      <?=$form2->field($model2, 'confirm_password')->passwordInput(['class' => 'form-control input_field_design', 'placeholder' => 'Confirm Password'])->label(false);?>
                   <?=$form2->field($model2, 'contact_no')->textInput(['class' => 'form-control input_field_design', 'placeholder' => 'Contact Number'])->label(false);?>
                <input type="text" name="hidden" value="signup" hidden="true">
                  <div class="form-group">
                    <?=Html::submitButton('Signup', ['class' => 'register', 'form' => 'form-signup', 'name' => 'signup-button'])?>
                </div>
        <?php ActiveForm::end();?>
    </div>
    </div>
</div> <!-- /form -->
<?php }?>
        </div>
      </div>
    </section>
    <?php
$url = Yii::getAlias('@web') . "/themes/chiefsrs/images/logo.png";
?>
     <div id="social_icons">
           <a href=""><img src="<?=Yii::getAlias('@web') . "/themes/chiefsrs/images/apple.png"?>" alt="apple logo and link to download on apple app store"></a>
           <a href=""><img src="<?=Yii::getAlias('@web') . "/themes/chiefsrs/images/facebook.png"?>" alt="facebook"></a>
           <a href=""><img src="<?=Yii::getAlias('@web') . "/themes/chiefsrs/images/twitter.png"?>" alt="twitter"></a>
           <a href=""><img src="<?=Yii::getAlias('@web') . "/themes/chiefsrs/images/insta.png"?>" alt="instagram"></a>
       </div>
    <!-- END section -->
     <section class="site-section" id="section-about">
      <div class="container">
        <div class="row">
          <div class="col-md-5 site-animate mb-5">
            <h4 class="site-sub-title">Our Story</h4>
            <h2 class="site-primary-title display-4">Welcome</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>

            <p class="mb-4">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            <!-- <p><a href="#" class="btn btn-secondary btn-lg">Learn More About Us</a></p> -->
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-6 site-animate img" data-animate-effect="fadeInRight">
            <img src="<?php echo Yii::getAlias('@web') . "/themes/chiefsrs/images/about_img_1.jpg" ?>" alt="About Us" class="img-fluid">
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

    <!-- END section -->

    <section class="site-section bg-light" id="section-contact">
      <div class="container">
        <div class="row">

          <div class="col-md-12 text-center mb-5 site-animate">
            <h2 class="display-4">Get In Touch</h2>
            <div class="row justify-content-center">
              <div class="col-md-7">
                <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              </div>
            </div>
          </div>
  <center><div id="loading" style="display:none;position:center;padding:2px;"><img src="<?php echo Yii::getAlias('@web') . "/themes/chiefsrs/images/loading.gif"; ?>" width="64" height="64" /><br>Loading..</div></center>
          <div class="col-md-7 mb-5 site-animate">
           <?php $form = ActiveForm::begin(['id' => 'contact_us', 'action' => Yii::$app->urlManager->createUrl("site/contact-us")]);?>

              <?php $model = new ContactUs();?>

            <?=$form->field($model, 'name')->textInput(['maxlength' => true])?>

            <?=$form->field($model, 'email')->textInput(['maxlength' => true])?>

            <?=$form->field($model, 'message')->textarea(['rows' => 10])?>

            <div class="form-group">
              <?=Html::submitButton(Yii::t('app', 'Send Message'), ['class' => 'btn btn-primary'])?>
            </div>
            <?php ActiveForm::end();?>
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-4 site-animate">
            <p><img src="<?php echo Yii::getAlias('@web') . "/themes/chiefsrs/images/about_img_1.jpg"; ?>" alt="About Us" class="img-fluid"></p>
            <p class="text-black">
              Address: <br> 121 Street, Melbourne Victoria <br> 3000 Australia <br> <br>
              Phone: <br> 90 987 65 44 <br> <br>
              Email: <br> <a href="mailto:info@yoursite.com">info@yoursite.com</a>
            </p>

          </div>

        </div>
      </div>
    </section>
   <script type="text/javascript">
$('body').on('beforeSubmit', "form#contact_us",function () {
     var form = $(this);
     // return false if form still have some validation errors
     if (form.find('.has-error').length) {
          return false;
     }
     // submit form
     $.ajax({
          url: form.attr('action'),
          type: 'post',
          data: form.serialize(),
          beforeSend: function(){
             $("#loading").fadeIn("slow");
          },
          success: function (response) {
               // do something with response
              if(response == "success"){
                alert("You Email has been sent successfully.");
                 location.reload();
              }else{
                alert("something Went wrong,Your mail is not sent.");
                location.reload();
              }
          },
          complete: function(){
            $("#loading").fadeOut();
      }
     });
     return false;
});
   </script>

frontend/views/site/restaurants.php
<?php 
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\models\Restaurants;
use common\components\Common;
use yii\widgets\Pjax;
$this->title = 'Chiefs RS';
?>    
         <?php Pjax::begin(['id' => 'gallery_r','timeout'=>100000,'enablePushState' => false,
        'clientOptions' => ['method' => 'POST']]); ?>
    <section class="site-section bg-light" id="section-news">
      <div class="container">

        <div class="row">
          <div class="col-md-12 text-center mb-5 site-animate">
            <h2 class="display-4">Restaurants</h2>
            <div class="row justify-content-center">
              <div class="col-lg-7 col-md-10">
                <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              </div>
            </div>
          </div>
 <?php if(!empty($models)){ 
          $count = 0;
          foreach ($models as $key => $restaurant) { ?>
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="media d-block mb-4 text-center site-media site-animate img-container">
              <img src="<?php echo Yii::getAlias('@web')."/uploads/".$restaurant->photo?>" alt="<?= $restaurant->photo;?>" class="img-fluid r_list">
              <div class="media-body p-md-5 p-4">
                <h5 class="mt-0 h4"><?php echo !empty($restaurant->name) ? $restaurant->name : "-"; ?></h5>
                <p class="mb-4"><?php echo !empty($restaurant->description) ? Common::get_substr($restaurant->description,70) : "-"; ?></p>

                    <p class="mb-0">
                <!--   <a href="<?php //echo Yii::$app->urlManager->createUrl(['site/restaurant-details',"rid"=>$restaurant->id]) ?>" class="btn btn-primary btn-sm">Read More</a> -->
                </p>
                <p class="mb-0">
                  <a onclick="window.open ('<?php echo Yii::$app->params['site_url'].Yii::$app->urlManager->createUrl(['site/restaurant-details',"rid"=>$restaurant->id]) ?>', ''); return false" href="javascript:void(0);" class="btn btn-primary btn-sm">Read More</a>
                </p>
              </div>
            </div>
          </div>
        <?php } 
      } ?>
        </div>
      </div>
    </section>
          <?php echo \yii\widgets\LinkPager::widget([
            'pagination' => $pagination,
           // 'options' => ['class' => 'pagination r_list'],
            ]);
             Pjax::end();
        ?>